# Generated by Django 2.2.5 on 2019-11-30 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tax_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(max_length=120)),
                ('Tax_id', models.CharField(max_length=40)),
                ('Name', models.CharField(max_length=120)),
                ('Address_line1', models.CharField(max_length=120)),
                ('Address_line2', models.CharField(max_length=120)),
                ('City', models.CharField(max_length=50)),
                ('Region', models.CharField(max_length=50)),
                ('Zip_code', models.IntegerField(max_length=50)),
            ],
        ),
    ]
