# Generated by Django 2.2.5 on 2019-12-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='billing_address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(max_length=120)),
                ('Business_name', models.CharField(max_length=120)),
                ('Name', models.CharField(max_length=120)),
                ('Address', models.CharField(max_length=120)),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Zip_code', models.IntegerField(max_length=50)),
            ],
        ),
    ]
