# Generated by Django 2.2.5 on 2019-12-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_billing_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing_address',
            name='Send_voice_Email',
            field=models.BooleanField(default=False),
        ),
    ]
