# Generated by Django 2.2.5 on 2019-12-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_billing_address_send_voice_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_amount', models.IntegerField()),
                ('Date', models.CharField(max_length=30)),
                ('Category', models.CharField(max_length=40)),
                ('Note', models.CharField(max_length=120)),
                ('Attached_file', models.CharField(max_length=120)),
            ],
        ),
    ]
